# Generated by Django 5.2.13 on 2026-04-13 14:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('demo_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Required text'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Leave this empty, then submit the page for translation to trigger the bug.', 'label': 'Optional text', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('required_text', 0), ('optional_text', 1)]], {})})),
            ],
            options={
                'verbose_name': 'Demo page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
